Update karma to the latest and greatest.  Doesn't work due to (probably) some double-loading of Jasmine, resulting in errors like: [2014-02-01 22:22:27.706] [DEBUG] config - Loading config /Users/skuenzli/dev/dev.weblog-ng/weblog-ng-client-javascript/config/karma.conf.js Chrome 32.0.1700 (Mac OS X 10.9.1) ERROR 	Uncaught TypeError: Property 'start' of object [object Object] is not a function 	at http://localhost:9876/karma.js:233 Chrome 32.0.1700 (Mac OS X 10.9.1): Executed 0 of 0 ERROR (0.033 secs / 0 secs)